packages:
- .

resolver: lts-18.28
compiler: ghc-8.10.7
compiler-check: match-exact
system-ghc: true
install-ghc: false

extra-deps: 
  - Spock-0.14.0.0
  - Spock-core-0.14.0.0
  - reroute-0.6.0.0
  - stm-containers-1.2
  - stm-hamt-1.2.0.4
  - primitive-extras-0.8